
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  authToken VARCHAR(255) NULL
);


CREATE TABLE IF NOT EXISTS posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  text TEXT NOT NULL,
  tags JSON DEFAULT NULL,
  userId VARCHAR(255) NOT NULl,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
